//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapitest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int quotenum { get; set; }
        public string quotetype { get; set; }
        public string contact { get; set; }
        public string task1 { get; set; }
        public System.DateTime duedate { get; set; }
        public string tasktype { get; set; }
    }
}
